server:
  port: 9191
spring:
  application:
    name: eureka-server-a
eureka:
  client:
    service-url:
      defaultZone:  http://localhost:9191/eureka/,http://localhost:9192/eureka/
    fetch-registry: false
  instance:
    hostname: servera