server:
  port: 9192
spring:
  application:
    name: eureka-server-b
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9191/eureka/,http://localhost:9192/eureka/
    fetch-registry: false
  instance:
    hostname: serverb