server:
  port: 9204
spring:
  application:
    name: eureka-client-c
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9191/eureka/,http://localhost:9192/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true
sidecar:
  port: 9203
  health-uri: http://localhost:9203/health