server:
  port: 9201
spring:
  mvc:
    favicon:
      enabled: false
  application:
    name: eureka-client-a
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9191/eureka/,http://localhost:9192/eureka/
msapmp:
  http:
    log:
      filter-uris: /h*,/h*/*