server:
  port: 9301
spring:
  application:
    name: service-consumer
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9191/eureka/,http://localhost:9192/eureka/
ribbon:
  connectTimeout: 30000
  readTimeout: 120000
