server:
  port: 9301
spring:
  application:
    name: service-consumer
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9191/eureka/,http://localhost:9192/eureka/
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 6000
        loggerLevel: basic

